### ISSUE TITLE
Unknown collector "paloalto"

### ISSUE THREAD

**Issue by riklempens** [infrasonar/toolkit#1]
**Describe the bug**

When trying to apply-assets containing the `paloalto` collector I received the following message:

```
Unknown collector "paloalto" (use --allow-unknown-collectors to ignore this error)
```

**To Reproduce**

Try to add or modify an asset containing the paloalto collector:

```
- name: palo01
  kind: PaloAlto
  mode: normal
  description: 'Cool firewall'
  labels:
  - Palo_Alto
  collectors:
  - key: paloalto
    config:
      _use: ''
      address: 127.0.0.1
 ```
**Workaround**

I was able to workaround this issue by using the `--allow-unknown-collectors` parameter.
